import axios from 'axios';

export default {
  name: 'ai',
  commands: ['gpt', 'ai', 'imagine'],
  handler: async (ctx) => {
    const { sock, jid, cmd, args } = ctx;

    if (!args) {
      const examples = cmd === 'imagine'
        ? 'Example: `!imagine a hacker in neon lights`'
        : 'Example: `!gpt how to check if a device is rooted`';
      await sock.sendMessage(jid, { text: `Usage: \`!${cmd} <prompt>\`\n${examples}` });
      return;
    }

    const loading = await sock.sendMessage(jid, { text: `⏳ *Thinking...*` });

    try {
      if (cmd === 'imagine') {
        try {
          const { data } = await axios.post('https://api.pollinations.ai/prompt', { prompt: args }, {
            params: { width: 512, height: 512, nologo: true },
            timeout: 30000,
            responseType: 'arraybuffer'
          });
          await sock.sendMessage(jid, { image: Buffer.from(data), caption: `🎨 *AI Generated*\n━━━━━━━━━━━━━━━━━━━━━\nPrompt: ${args}\n━━━━━━━━━━━━━━━━━━━━━\n_Generated by Pollinations AI_` });
        } catch {
          await sock.sendMessage(jid, { text: `🎨 *Imagine: ${args}*\n━━━━━━━━━━━━━━━━━━━━━\n⚠️ Image generation failed.\nOpen this link in browser:\n🔗 https://image.pollinations.ai/prompt/${encodeURIComponent(args)}\n━━━━━━━━━━━━━━━━━━━━━` });
        }
      } else {
        const apiKey = process.env.GEMINI_API_KEY || null;
        let reply;
        if (apiKey) {
          try {
            const { data } = await axios.post(
              `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
              { contents: [{ parts: [{ text: args }] }] },
              { timeout: 15000 }
            );
            reply = data?.candidates?.[0]?.content?.parts?.[0]?.text || 'No response from AI.';
          } catch {
            reply = '⚠️ Gemini API error. Set GEMINI_API_KEY or try again.';
          }
        } else {
          try {
            const { data } = await axios.get(`https://api.leaky.ai/v1/chat/completions`, {
              params: {
                model: 'gpt-4o-mini',
                messages: JSON.stringify([{ role: 'user', content: `Answer concisely: ${args}` }]),
                max_tokens: 500
              },
              timeout: 10000
            });
            reply = data?.choices?.[0]?.message?.content || data?.response || 'No response.';
          } catch {
            reply = `⚠️ No API key configured.\nSet GEMINI_API_KEY env var for AI.\n\nYour prompt was: ${args}`;
          }
        }
        const maxLen = 4000;
        if (reply.length > maxLen) reply = reply.slice(0, maxLen) + '\n\n_...truncated_';
        await sock.sendMessage(jid, { text: `🧠 *AI Response*\n━━━━━━━━━━━━━━━━━━━━━\n${reply}\n━━━━━━━━━━━━━━━━━━━━━` });
      }
    } catch (e) {
      await sock.sendMessage(jid, { text: `❌ ${cmd} error: ${e.message}` });
    }
  }
};
